### ISSUE TITLE
Blockquotes does not seem to render

### ISSUE THREAD

**Issue by ErikWallstrom** [fabiocolacio/Marker#111]
Try this

```markdown
> Hello World

Hello World
```

Both of them seem to produce the same result which isn't the expected

**Comment by Mandarancio** [comment]
This is the output on my setup (master branch, last commit):

![output](https://user-images.githubusercontent.com/276686/35047975-efe0fa68-fb9b-11e7-8fa0-03c501079d07.png)

It is correct right? Can you send me a screenshot of your problem? Thanks!

**Comment by ErikWallstrom** [comment]
I installed the AUR package just now. Here is what I am seeing: 

![screenshot from 2018-01-19 22-41-56](https://user-images.githubusercontent.com/15019604/35172966-05a68b72-fd6a-11e7-9a82-c57b0a93fe59.png)

Is there a setting I am missing? Love the program by the way!

**Comment by Mandarancio** [comment]
When did you installed marker? 

I just try install ```marker-git``` via ```yaourt``` and it worked as supposed to.

**Comment by ErikWallstrom** [comment]
@Mandarancio I installed it about 40 minutes ago via pamac-aur. Also tried it on another computer with the same results

**Comment by Mandarancio** [comment]
@ErikWallstrom The only difference I see is the ```Marker``` title in between the tool-bar and the editor window in your screenshot, but I do not know if depends from the theme or some gnome settings.

The weird part is that the ```markdown``` to ```html``` conversion is done internally so it should not depend on your system. 
Have you tried to clone and compile the code your self and to see if the problem persist? 

By the way thank you very much for the issue reporting and for the collaboration!

**Comment by fabiocolacio** [comment]
@Mandarancio perhaps one of the hoedown extensions like mermaid is somehow interfering with the block quotes?

As a side-note @ErikWallstrom what desktop environment are you using? This is designed as a gnome app, but i would like it to look good on any gtk desktop. If you disable 'use gnome appmenu' in the preferences it should improve the look of the app on desktops that dont support the appmenu.

**Comment by Mandarancio** [comment]
@fabiocolacio  good question, however I'm using all the extensions enabled, but would be interesting to know witch prefrences are @ErikWallstrom  using.

**Comment by ErikWallstrom** [comment]
I just found the reason. The default css theme (swiss.css) does not seem to differentiate text with block quotes, not sure if this is intended. The issue is fixed when using `Github.css`. Sorry if I brought up a non-issue

**Comment by Mandarancio** [comment]
Ok perfect! No problem! Please keep reporting issues!
