### ISSUE TITLE
Icons in the upper left corner of sketcher are blurry (tested on hidpi screen)

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#115]
This may be a result of scaling on a hidpi screen.

**Comment by fabiocolacio** [comment]
The stock icons look fine, but not the custom ones. This is odd because they are svg icons so they should scale properly...

**Comment by Mandarancio** [comment]
Could you post a screen shot of the problem? I will try as well on my laptop screen that is hidpi, are you using any  scaling factor?

**Comment by fabiocolacio** [comment]
![blurryicons](https://user-images.githubusercontent.com/5248352/35074075-097d5c8c-fba1-11e7-9491-f235f1152c6e.png)

As you can see, the icons are the left are aliased unlike those on the right.

I also just noticed that the icons are a lighter shade than the stock icons, but that is easy to change.

**Comment by fabiocolacio** [comment]
I am using the 2 times scaling factor through gnome shell

**Comment by Mandarancio** [comment]
It's real unfortunate that gnome does not have any stock icons for such common actions (there is only for the text), I will look into it.

**Comment by Mandarancio** [comment]
e7183fe in the branch better-sktecher should have fix the problem (at least on my hidpi configuration works nice)/

**Comment by fabiocolacio** [comment]
I tested it and It looks much better on my machine as well. Good work!
