### ISSUE TITLE
Make a website

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#116]
I would like to create a simple webpage for the app with information and screenshots about Marker.

I would like it to include the following:
* guides for using some of the more advanced features such as the latex formulas and charter plots.
* instructions for downloading flatpaks (once we actually have a flatpak working) of the application.
* a 'roadmap' section detailing what is to come in future releases

It can be hosted on github, or elsewhere if there is a better suggestion.

**Comment by Mandarancio** [comment]
You can do it using github, somewhere in the repository settings there is the option to create a web page for the project.
