### ISSUE TITLE
Removing useless branches

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#120]
I suggest to remove the merged branches for a cleaner repository. To do so:

```
git branch -d BRANCH_NAME
git push origin :BRANCH_NAME
```

I already removed mines (If I did not forget any).

**Comment by fabiocolacio** [comment]
This can also be done from github in the branches section btw. I just closed most of them

**Comment by Mandarancio** [comment]
Oh! Good to know! Thank you!
