### ISSUE TITLE
Sidebar Design

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#121]
Hey @Mandarancio I have been looking at the sidebar branch and testing it out. From a user's perspective, I really like it so far, but I have a few concerns with the implementation right now.

When I created the ``MarkerEditor`` class, my intention was that each ``MarkerEditor`` would be associated with one file, whereas the ``MarkerWindow`` would manage multiple ``MarkerEditor``s. I designed ``MarkerEditor`` in a way that would make this design much easier to implement and maintain.

Your current implementation in the sidebar branch only ever uses one instance of ``MarkerEditor``, which defeats the purpose of the new redesign.

In other words, instead of the sidebar being implemented as part of ``MarkerEditor``, it should be implemented as part of ``MarkerWindow``. And instead of managing a list of files, and a list of names, you can just manage one single list of ``MarkerEditor``s. You can call ``marker_editor_get_title ()`` to avoid having to manage the names list, and ``marker_editor_get_file ()`` to avoid having to manage the files list. The main window can have a paned view with the sidebar and the current ``MarkerEditor``. The ``MarkerEditor`` class should require little to no modification for that design to work.

I'm sorry if I was not clear about my intentions before, but hopefully this makes sense. I thought it would be better to share my concerns now than wait for the feature to be fully implemented :)

**Comment by Mandarancio** [comment]
Ok I understand the point. However in such way each editors could have different view mode (that actually make sense) , how you would manage it in the settings? 

Anyway I had to rewrite all the tree model so it does not change much moving the tree view out of the editor.

**Comment by fabiocolacio** [comment]
The idea i had is that the setting control the *default* view mode when you create or open a document. Then, if the user wants, he can have different view settings for each open file.

**Comment by Mandarancio** [comment]
Ok so it's like is implemented now :+1:
