### ISSUE TITLE
Add appstream metadata

### ISSUE THREAD

**Issue by bertob** [fabiocolacio/Marker#122]
For publishing on Flathub (as suggested in #40 and #114), an appstream metadata XML file is needed.

This is the official documentation:
https://www.freedesktop.org/software/appstream/docs/chap-Quickstart.html

**Comment by Mandarancio** [comment]
I added the metadata in the commit ba187e2 and are now correctly installed in the folder ```/usr/share/metainfo/```.
We are still missing something for Flathub?

**Comment by Mandarancio** [comment]
I belive that in #125 @jsparber  has fixed the issue right?

**Comment by jsparber** [comment]
We still need to fix issues pointed out by 
```
appstream-util validate data/com.github.fabiocolacio.marker.appdata.xml
```
I think @bertob is fixing them.

**Comment by Mandarancio** [comment]
Great job @bertob !
