### ISSUE TITLE
View mode in header bar

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#124]
Could be nice to have a ```ButtonBox``` with 4 combo buttons for switch between view modes. Something like in the ```Finder``` view mode:
![finder_view_mode](https://user-images.githubusercontent.com/276686/35288092-233221ae-0064-11e8-9675-8b8624681051.png)

**Comment by fabiocolacio** [comment]
I think it looks better in the popover menu but maybe you can convince me if you send me a screenshot with your idea. I have been considering adding some wysiwyg controls so I don't want the headerbar to get too crowded.

**Comment by Mandarancio** [comment]
After some thought I think it make more sense as well in the menu, but I think it would be nicer to have some combo button with nice symbolic icon just under the zoom buttons instead of the sub menu textual entries as now. (I'm not sure my thoughts were clear enough)

**Comment by fabiocolacio** [comment]
That can work 👍
