### ISSUE TITLE
Add table popup 

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#128]
It would be great to have a short-cut + pop up window to add tables with number of columns and title alignment.

**Comment by fabiocolacio** [comment]
I like this idea. Tables can be very cumbersome to create in markdown, but a small amount of automation would certainly relieve this issue. @gnacho has made a greate mockup of a markdown editor, and shows his idea of how this menu might look: https://github.com/gnacho/Gnome-MD . 

Another way to do this could be the the grid-like interface used in LibreOffice and other document processors.

**Comment by Mandarancio** [comment]
The mockup is great and I like the idea to have an option secondary tool bar with some extra commands as well as I really like the table of contents in the side bar. 

I think I prefer the @gnacho popup than the classical grid-like interface, I select always the wrong number of rows/columns! 
However I think that the number of rows is not so important as the rows are very easy to insert, maybe add some sort of option for the title alignment (but is also easy to change).

**Comment by fabiocolacio** [comment]
I will add this when I add the wysiwyg from #43.
