### ISSUE TITLE
Use GtkFileChooserNative

### ISSUE THREAD

**Issue by jsparber** [fabiocolacio/Marker#133]
To improve platform compatibility Marker should use GtkFileChooserNative instate of GtkFileChooser. Especially for better integration for flatpak, but not only.
https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html

**Comment by fabiocolacio** [comment]
I made the switch in the latest commit: https://github.com/fabiocolacio/Marker/commit/489cec84a0b7932af4203dc3aacff50a8399530e.

Do I need to make another release?

**Comment by jsparber** [comment]
Super fast \o/
I'm gonna try it tomorrow, if everything works we should do a new release.

**Comment by jsparber** [comment]
Ok managed to test it. Can you create a new release?

**Comment by fabiocolacio** [comment]
I just made a new one as ``2018.01.25``
