### ISSUE TITLE
Scroll Preview when appending to the end of a document

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#135]
When typing out notes that take up more than one screen's height, the editor pane of course follows your cursor as you type, but the preview will not scroll down to show the newly added text.

This means that you are stuck having to constantly scroll the right pane down to follow your work.

**Comment by Mandarancio** [comment]
In commit a1f7bc0 I implemented the following: if the scroll is at the bottom of the preview it stick to the bottom at the update to avoid to scroll down.

However this do not check if the cursor is on the last row of the editor, but it improve the usability anyway.

**Comment by fabiocolacio** [comment]
On my machine the scroll lock never gets triggered for some reason. I will try to investigate it some more.

**Comment by Mandarancio** [comment]
I forgot to tell than to test the extension you have to install it using ```sudo ninja install``` as marker is looking for the library in the system path.

**Comment by fabiocolacio** [comment]
Ah yes, I totally forgot. That fixed it for me, thanks.
