### ISSUE TITLE
Using accents disables CSS in preview

### ISSUE THREAD

**Issue by rodolpheh** [fabiocolacio/Marker#136]
When there is an accent in the file path or an accent in the content of the file, the CSS preview fall back to the default, unstyled one. I'm using the version 2018.01.09 on ArchLinux, installed from the AUR.

Let me know how I can help debug this.

**Comment by Mandarancio** [comment]
The wierd thing is that the exported html is actually correct but the preview do not work

**Comment by Mandarancio** [comment]
After enabling ```webkit_settings_get_enable_write_console_messages_to_stdout``` of the webkit viewer I get this messages once I type any accented character:

```
file:///usr/local/share/com.github.fabiocolacio.marker/scripts/katex/katex.min.js:1: CONSOLE ERROR SyntaxError: Invalid character '\u286e'
file:///usr/local/share/com.github.fabiocolacio.marker/scripts/katex/contrib/auto-render.min.js:1: CONSOLE ERROR SyntaxError: Invalid character '\u286e'
file:///usr/local/share/com.github.fabiocolacio.marker/scripts/highlight/highlight.pack.js:1: CONSOLE ERROR SyntaxError: Invalid character '\u2a2f'
file:///usr/local/share/com.github.fabiocolacio.marker/scripts/mermaid/mermaid.min.js:1: CONSOLE ERROR SyntaxError: Invalid character '\u286e'
file://unnamed.md/:15:29: CONSOLE ERROR ReferenceError: Can't find variable: renderMathInElement
file://unnamed.md/:16:14: CONSOLE ERROR ReferenceError: Can't find variable: hljs
file://unnamed.md/:17:17: CONSOLE ERROR ReferenceError: Can't find variable: mermaid
```

**Comment by Mandarancio** [comment]
The commit 2319c2e should have fix the problem. @fabiocolacio could you try with the new code and tell me if it works? If so could you make a release with this problem fixed?

**Comment by fabiocolacio** [comment]
That solved it for me. The release has been made.

**Comment by Mandarancio** [comment]
bug is still problematic as @bertob reported in issue #170

**Comment by Mandarancio** [comment]
The problem is really due to `webkit2gtk` as even `Epiphany` (gtk browser based on the same webkit library) on has the same issue as shown in the screenshot below, where both `Firefox` and `Epiphany` (aka `Gnome Web`) render the same local `html` file from a folder with accent (in the example `/tmp/perchè/test.html`):

![screenshot from 2018-03-12 12-34-32](https://user-images.githubusercontent.com/276686/37281556-c136af2a-25f1-11e8-91c4-25c146ea776c.png)

I will submit the  issue to the webkit2gtk team

**Comment by somas95** [comment]
I had a very similar issue. WebKit has a bug with utf-8 encoded files. For me encoding the css files in utf-16 solved the issue

**Comment by Mandarancio** [comment]
@somas95: I tried to encode the CSS files as utf-16 but nothing changed do you also encoded the html in utf-16? or the URI?

**Comment by somas95** [comment]
Nope, only the .css file
Do you know how to inspect GtkWebViews?

**Comment by Mandarancio** [comment]
Mmmm... No I do not know how to inspect a GtkWebView. How does it work?

**Comment by somas95** [comment]
It's easy. Run your app with
``WEBKIT_INSPECTOR_SERVER=127.0.0.1:1234 marker``
then open Web (it needs to be the gnome web browser) and go to
`inspector://127.0.0.1:1234`

**Comment by somas95** [comment]
Check if you can read all the source files. For me the .css ones were totally unreadable, and it was because WebKit was expecting utf-16 encoded files, and I was providing utf-8 ones.

**Comment by Mandarancio** [comment]
@somas95 First thanks for the explanation.

I successfully used the inspector and I experienced the following:
 - No apparent difference when using utf-8 or utf-16 files 
 - When there is an an accent or a special char in the path the css file are not accessible from the inspector (I click on the link and no file is open) but no error or warning appear in the console

**Comment by somas95** [comment]
Well, that's interesting. At least now you know another tool for debugging this issue :)

**Comment by Mandarancio** [comment]
Now the problem should be  fixed as I am not linking the css but I am loading the style directly into the HTML.
