### ISSUE TITLE
Change binary name to marker

### ISSUE THREAD

**Issue by jsparber** [fabiocolacio/Marker#139]
Since most apps have as name for the binary only the application name not the dbus id, we should change it to "marker". I think its confusing right now if you try to lunch Marker form the terminal. What do you think?

**Comment by fabiocolacio** [comment]
Agreed, it is quite tedious to type out the ``com.github.fabiocolacio.marker`` each time. I have changed it to simply ``marker`` in commit https://github.com/fabiocolacio/Marker/commit/03655169d6394a8f832711ae2ededf13577aa951.

**Comment by jsparber** [comment]
I think we need also to change the name in the desktop file and flatpak manifest and maybe in some other files

**Comment by fabiocolacio** [comment]
Yikes I totally forgot about all that. I'll take care of that now

**Comment by fabiocolacio** [comment]
As a side-note @jsparber, is there any reason to keep updating the flatpak manifest that is part of the main Marker repository. It has already fallen behind the one in FlatHub repository, and I am tempted to remove it if we don't need two manifests.

**Comment by jsparber** [comment]
I'm still not sure about how to keep it in a up-to-date state in my own projects. For now i think the best would be to remove it.

**Comment by fabiocolacio** [comment]
Allright I believe I changed everything in the Marker repository for this. In the flatpak manifest, would it be the "Command" key that I change?

**Comment by fabiocolacio** [comment]
Okay I believe I fixed everything now

**Comment by jsparber** [comment]
Can you also make a new release and add it to the manifest.
Because for now it builds still the version with the long name, but tries to run "marker". So right now the flathub build is broken.

**Comment by thebitstick** [comment]
Flatpak users here:
Found this issue and wanted to bring up a possible name change for Flathub.
Instead of `com.github.fabiocolacio.marker`, it should be `io.github.Marker`.

This is conventional and is what most if not all developers use for Flatpaks.
