### ISSUE TITLE
Internal Scholarity Markdown support

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#145]
I would like to add internal support to [Scholarity Markdown](http://scholarlymarkdown.com/) a markdown language extension for ```scholarly and academic communication```

**Comment by Mandarancio** [comment]
Instead of using scholarity that is dead I'm implementing a fork of hoedown with few additional features:
(scidown)[https://github.com/Mandarancio/scidown/]

**Comment by fabiocolacio** [comment]
Great idea!

This can be included in the installation as one of the backends when the backend system gets implemented.

Do you plan to add all the features of our current custom version of hoedown?

If that is the case, we can replace the default engine with vanilla hoedown, and users can select this backend if they want the extra features.

**Comment by Mandarancio** [comment]
So I plan to add two internal engine for the moment: hoedown and scidown to see how the two performs and if scidown can do (it should) everything hoedown does. 
I create a new branch to test it out.
For the moment scidown implements most of the features of `scholarity markdwon` but with a slightly different (easier for me)  syntax.

**Comment by Mandarancio** [comment]
The branch scidown now support [SciDown](https://github.com/Mandarancio/scidown/) @jocap and @fabiocolacio  if you want try it and report bug/missing functionality would be great!
The additional functionality are:
 - YAML header: specifing title, authors, affiliations, keywords 
 - figures, tables and listing with id, numbering and captioning
 - equations with id and numbering
 - reference to figures, tables, listening and equations via id (#id)
 - include external file or bibliography
 - abstract special section
More information in the readme of [SciDown](https://github.com/Mandarancio/scidown/)
