### ISSUE TITLE
Dynamic coloring for custom icons

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#151]
As pointed out in issue #150 by @Maestroschan, the custom icons in sketcher should better match the colors of the current icon set if possible.

![](https://i.imgur.com/4o2uGnz.png)

**Comment by Maestroschan** [comment]
It looks like default icons themes' SVG files don't really care about color and adapt themselves to what the GTK theme ask, could these images be treated as normal icons ?

**Comment by Mandarancio** [comment]
Right now I implemented the custom icon theme as `Adawita` does: dark non scalable icons and light scalable icons, however it does not switch automatically as it does with `Adawita`, could you try if it's true also on your configuration?

**Comment by fabiocolacio** [comment]
It doesn't switch for me either

**Comment by Maestroschan** [comment]
> could you try if it's true also on your configuration?

There are a lot of things i don't understand and/or i didn't do well...

- did i clone the wrong thing last week ? i didn't have the `data/icons/` folder, i was still with `src/resources/ui/icons/`, maybe i stupidly recompiled the version i downloaded last month, and it was why i had wrong icons ? :/

So i reinstalled things from zero. And then:
- icons are in the sources, and in `/usr/local/share/com.github.fabiocolacio.marker/`, but still not in `/usr/share/icons/hicolor/`, so no icons at all in the window (i guess the install script has been studied for flatpak ? btw i didn't even have reading permission for most files in `/usr/local/share/com.github.fabiocolacio.marker/`, which was breaking some minor things in the Preferences window)
- i copied icons manually to the right folder, so they appear! smaller than before for some reason, and still black
- i renamed svg white icons with "-symbolic" at the end of their names, modified icon names in `marker-sketcher-window.ui`, and `sudo ninja install` again

Conclusion: [good news](https://i.imgur.com/hxcuaHT.png) and [less good news](https://i.imgur.com/Mdhtf44.png)

----

"Maybe the issue come from my horrific frankendebian and its anarchic /home/me/ ?" I then thought, "I should try on my other Linux OS: the glorious Solus!" [to be continued in an other issue]

**Comment by Mandarancio** [comment]
First of all thank you for the tests and results you posted here! I will defenitly add the `-symbolic` and try to understand why use the correct in some cases and not in others!

**Comment by Mandarancio** [comment]
Ok problem fixed (at least on my setup). 

![sketcher_light](https://user-images.githubusercontent.com/276686/36202441-1b391e72-1184-11e8-98c4-9398365eeb10.png)
![sketcher_dark](https://user-images.githubusercontent.com/276686/36202442-1ca2fada-1184-11e8-9d7c-86dd4d236993.png)
