### ISSUE TITLE
Settings schema not installed ?

### ISSUE THREAD

**Issue by Maestroschan** [fabiocolacio/Marker#155]
after compiling Marker on Solus, i tried to run it and:

`(marker:6887): GLib-GIO-ERROR **: Settings schema 'com.github.fabiocolacio.marker.preferences.editor' is not installed`

idk why: it worked with Debian, and with Solus i had no difficulty copying the xml file at the correct place and compiling it (then it worked perfectly).

Probably a Solus bug (while i was installing Marker, it was dramatically failing its updates in the background), but just in case, i report it

**Comment by fabiocolacio** [comment]
Hi @Maestroschan 

Compiling the code alone is not enough to run the program. You need to install everything with ``sudo ninja install`` before you can run it. Is that the issue you are running into?

How are you building and installing the project? Are you using the ``configure`` script, or are you running meson directly like it shows in ``README.md``?

I don't usually build using the ``configure`` script so it is entirely possible that there is a bug with it

**Comment by Maestroschan** [comment]
When i say "compiling" it's more "copy-pasting all commands at the bottom of the readme", i've no idea what ninja/meson/etc. actually do :D

**Comment by fabiocolacio** [comment]
Interesting, so you ran all those commands before trying to run it, and it still didn't work?

And what do you mean when you say you don't have a ``.desktop``?

I will try this in a Solus virtual machine to see if I can reproduce the problem.

**Comment by Maestroschan** [comment]
> And what do you mean when you say you don't have a .desktop?

The `com.github.fabiocolacio.marker.desktop` file hasn't been copied to `/usr/share/applications/`

I just tried the same with Fedora and the installation was fine.

(And what i said in #151 about adding "-symbolic" at white icons' names is true here again.)

**Comment by fabiocolacio** [comment]
I tried to build this in a Solus vm, but meson doesn't seem to install properly on Solus when using ``eopkg``.

Every time I try to run meson, I get ``ImportError: No module named 'mesonbuild'``
