### ISSUE TITLE
No style & no pictures with some paths

### ISSUE THREAD

**Issue by Maestroschan** [fabiocolacio/Marker#159]
https://www.youtube.com/watch?v=dcugzVSY4kw

the first file was in a folder with a "É" in its path, you can see there is no CSS (or only a minimal CSS ?)

then in my ~/ folder, the CSS worked

Btw since pictures were in the folder with a É too, they don't appear. Replacing the É by a E allowed me to see the file as expected

**Comment by Mandarancio** [comment]
This issue is already known as #136 

It is due to `webkit2gtk` that has some kind of problem with non-standard character and utf-8 encoding. I'm trying to fix it.  :) 

Thanks anyway for the comment and the very clear report!
