### ISSUE TITLE
Ctrl+N shortcut infinitely creates new documents

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#160]
When using the ``Ctrl``+``N`` shortcut, new documents are continuously created in the sidebar until I stop the program.

I tested this on two machines. It wasn't always like this, so there must have been an update that conflicted with this functionality.

@Mandarancio are you able to reproduce this?

**Comment by Mandarancio** [comment]
No I was not able to reproduce this problem (nor in `master` or in `scidown` branch), however in the past I had a similar problem and clean the build directory and rebuild everything solved the problem for me.

**Comment by Mandarancio** [comment]
Have you reproduced the problem?

**Comment by fabiocolacio** [comment]
I was able to reproduce it when I created this bug, but I can't seem to reproduce it anymore...

I suppose it must have been an issue with my setup.

I will close this for now, since nobody can reproduce it. I will re-open this if it happens again.
