### ISSUE TITLE
Double appmenu (gmenu)

### ISSUE THREAD

**Issue by diazbastian** [fabiocolacio/Marker#164]
In non-GNOME desktop environments or by changing the configuration from GNOME-Tweaks, the appmenu can be displayed in the application window. In the case of Marker this shows 2 menu entries instead of 1.

Tested on fedora 27 XFCE, Marker 2018.01.09 from flathub

![marker](https://user-images.githubusercontent.com/5126124/37184438-1ee12482-231a-11e8-93a2-5136807b8871.png)

**Comment by fabiocolacio** [comment]
If you go to disable ``Preferences>Window>Use GNOME appmenu (requires app restart)``,  the appmenu will be removed, and those entries will be put in the hamburger menu of the window. This feature was added to better accommodate non-GNOME desktops.

Coming in a future update, there will also be an option to use a traditional menubar layout with no csd or appmenu.

With these two options available, the app will integrate well with non-GNOME desktops.

**Comment by diazbastian** [comment]
@fabiocolacio Thanks, I had already seen that option, however, it doesnt do anything (when restarting the app, it returns to its default configuration). Anyway, for GNOME users moving the appmenu inside the window is a valid option and some GNOME-based distros use this default configuration (eg Elementary)

Thank you

**Comment by fabiocolacio** [comment]
Hi @diazbastian,

Thanks for the feedback. I will look into resolving the double-appmenu issue, and reply here with any developments that occur.

With regards to the preferences not being saved, this is a known bug with the flapak version, which is being worked on [here](https://github.com/flathub/com.github.fabiocolacio.marker/issues/3). You can either wait for the update to roll out to flathub users, or you can compile a release from github if you would like to resolve the issue immediately.

**Comment by fabiocolacio** [comment]
This was finally fixed with commit https://github.com/fabiocolacio/Marker/commit/e14e639de780862fb27465ebfa390b04f4e60bf5
