### ISSUE TITLE
New flatpack relase

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#165]
I think is time to make a new release and update the flatpack code. I just saw a quite recent (26.02) [video](https://www.youtube.com/watch?v=czKrZIi1G0k) on youtube in which few bugs and issue we have solved still are there (e.g. dark icon on dark theme).

**Comment by fabiocolacio** [comment]
Thanks for letting me know, I just made a new release, and updated the flathub repo.

I'm not entirely sure how flathub works, but I think users will get the update now.
