### ISSUE TITLE
Make release tarballs

### ISSUE THREAD

**Issue by Cogitri** [fabiocolacio/Marker#166]
It'd be great if you could do release tarballs instead of just offering github's automatically created ones, since those don't include any submodules ( basically making them unusable currently )

**Comment by Mandarancio** [comment]
Yes looks like a good Idea. I will try to upload a custom tarball to the last release with all sub-modules correctly initialized. 

Thanks for the info!

**Comment by Cogitri** [comment]
Great, thanks!

**Comment by Cogitri** [comment]
Maybe it'd be a better idea to name the release tarballs Marker-$VERSION instead of Marker.$VERSION, most projects use a `-` instead of a `.`
