### ISSUE TITLE
Editor should be automatically focussed when application is opened

### ISSUE THREAD

**Issue by svartrev** [fabiocolacio/Marker#168]
When the application is opened, the editor pane should be automatically focussed such that one can just start typing, instead of having to first click inside the pane to focus it. As far as I can see, after opening the application, there is no way to start typing text without using the mouse  to select the editor pane, as there seems to be no way to focus this from the keyboard.

**Comment by fabiocolacio** [comment]
Thanks for the input.

This is now fixed in commit 74d9767f8a965c8a5c2b8e33972f41db47a24241
