### ISSUE TITLE
No css loaded in preview when rendering a saved file

### ISSUE THREAD

**Issue by bertof** [fabiocolacio/Marker#170]
Hi, I'm using Marker on Arch Linux, installed from AUR.
I noticed the same bug both in the newest [release version](https://aur.archlinux.org/packages/marker) in the [latest version](https://aur.archlinux.org/packages/marker-git/), having all the optional dependencies installed.
Both when a file is saved and when one is opened the preview panel turns to white, like a standard css of a webpage, and does not compile katex strings.

Apparently the only thing that triggers this behaviour is if the file is saved in a path containing accented characters; in my case something like /home/bertof/Documenti/Università/file.md

I can reproduce it if it's useful.

**Comment by Mandarancio** [comment]
Yes this bug is well known and we are trying to solve it is the same of issue #136. It is something due to character encoding and webkit2gtk.

Thanks for the  well documented issue, I will merge this with the old issue if is fine for you!

**Comment by bertof** [comment]
Sorry for the double issue, I didn't find it searching, before.
Sure, that sounds good to me.
