### ISSUE TITLE
error compiling marker from latest git version

### ISSUE THREAD

**Issue by dasnoopy** [fabiocolacio/Marker#176]
Hi, I tried compile and use Marker on my archlinux box using the [AUR](https://aur.archlinux.org/packages/marker-git/) package listed in the readme,  but process failed with this error: 
```
==> Starting prepare()...
error: Server does not allow request for unadvertised object be4b5db8c6dfd5d3e15533e3155b4778428f6341
Fetched in submodule path 'src/scidown', but it did not contain be4b5db8c6dfd5d3e15533e3155b4778428f6341. Direct fetching of that commit failed.
==> ERROR: A failure occurred in prepare().
```
just for the record I tried to compile it manually,  following build instructions and the same error occurred :
```
$git submodule update --init --recursive
Submodule 'src/scidown' (https://github.com/Mandarancio/scidown.git) registered for path 'src/scidown'
Cloning into '/home/public/Documents/AUR/Marker/src/scidown'...
error: Server does not allow request for unadvertised object be4b5db8c6dfd5d3e15533e3155b4778428f6341
Fetched in submodule path 'src/scidown', but it did not contain be4b5db8c6dfd5d3e15533e3155b4778428f6341. Direct fetching of that commit failed.
```

thanks in advance  for any help
Andrea

**Comment by Mandarancio** [comment]
Hi Andrea,

Thanks for reporting the problem, I tried installing the aur package `marker-git` on my machine without success  as well as he manual install...

It was due a commit on my local [scidown](https://github.com/Mandarancio/scidown/) that I forgot to push. 

I am really sorry for the inconvenient. 

Martino
