### ISSUE TITLE
Using external editor

### ISSUE THREAD

**Issue by jbjjbjjbj** [fabiocolacio/Marker#177]
I don't know if this is already implemented, but a option to use your own editor would be great. 

Would it be possible to make Marker automatically load from the file when it updates, and that way edit the file in another editor like vim etc. A bit like the [openscad](http://www.openscad.org/) program.

**Comment by Mandarancio** [comment]
This is a very interesting idea. I suppose that in preview mode we could regularly check if the file has been changed.

I will definitely look into it.

**Comment by fabiocolacio** [comment]
@Mandarancio I think the best way to do this would be with [``GFileMonitor``](https://developer.gnome.org/gio/stable/GFileMonitor.html).

You just have to get a ``GFileMonitor`` object for a file, and connect the ``:changed`` signal to refresh the preview.

**Comment by Mandarancio** [comment]
Yes I just committed the feature. Commit  859c6c0 uses `GFileMonitor` to monitor the open file only when using the `PreviewOnlyMode`.  In future it would be useful to always monitor and to show a warning when something else modify the opened file.

**Comment by sadid** [comment]
I'm trying to achieve the same thing, edit in vim and preview in marker. However, as I've checked this feature isn't available. Right?
