### ISSUE TITLE
Separate frontend and backend

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#179]
I would like to create a backend library *libmarker*, allowing some of *Marker*'s most powerful features to be used in other projects. This would allow people to easily incorporate *Marker* into other projects. This also makes it easier to create other frontends such as a cli frontend or a qt frontend.

I'm not yet sure if I will host it in a separate repository, or if I should simply add an option in meson to build the library on its own.

**Comment by Mandarancio** [comment]
Which kind of functionality would you like to put in the backend library? 

Maybe I'm wrong or I'm forgetting something (that is very probable) but in my opinion most of our backend functionality are inherited from  `scidown` that is already a library (and an executable to create `html` and `latex` files from the md), and the `pdf` rendering are inherited from `webkit2gtk`. 

Most of the interesting features of Marker are the graphical Ux and HMI but I found that is very specific to this project.  However It could be interesting to make a proper `sketcher` and release it independently like a sort of `paint` for Gnome.

**Comment by fabiocolacio** [comment]
I suppose you are right. There are only a few features that Marker adds on top of scidown, such as specifying external js and css files at compile-time, but it would make more sense to just add this to scidown rather than creating a new library altogether. I will close this issue.

On a completely tangential note, @Mandarancio, I have been thinking the same thing about sketcher (although with a more specific use in mind). Even before I started work on *Marker*, I have been toying around with the idea of creating a pixel-art editor, which would have support for layers, alpha channels, animations, exporting sprite-sheets, and other useful features for game-devs and pixel-art enthusiasts. I have not seen anything like this that uses native linux toolkits. If this is something you are interested in, let me know, and maybe we can work together on it! 😁
