### ISSUE TITLE
RTL Support

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#184]
@ronhasson and @fabiocolacio : 
As explained in #183 I had to revert the pull as there were issues with KaTeX and MathJax (and maybe more). 

A possible workaround is to create a small additional `css` (`data/common/rtl.css`) with all the tunes for RTL writing and adding an option to enable RTL in the preferences, when enabled we additionaly load `rtl.css` into the html. What do you think?

**Comment by ronhasson** [comment]
Interesting, when I tested with some small KaTeX it worked, would you mind sharing what heppens with what markup?

And enabling rtl would be wierd, i can just probably update the css selector so it wont affect KaTeX.

I wont be home for at least 5 hours, so I will test this later

**Comment by Mandarancio** [comment]
I was trying the file [`test/markdown_test.md`](https://github.com/fabiocolacio/Marker/blob/master/test/markdown_test.md).

The markup is:
```markdown
$$
\begin{cases}
....
\end{cases}
$$
```
and 
```markdown
@equation 
(x+1)^2=-y 
@/
```
Let me know if you experience the same problem or if you find a way to fix it.

**Comment by ronhasson** [comment]
ok now this is even weirder, when I made it exclude <span> elements from the unicode-bidi rule - some span elements just flipped direction but others didn't

![screenshot from 2018-04-07 12-28-57](https://user-images.githubusercontent.com/7431072/38453529-cd0dc180-3a5f-11e8-825a-0f6c75886b8a.png)

```css
* ~ span{
unicode-bidi: plaintext;
}
```
and again the export to html just seems fine, it's just the preview.

**Comment by ronhasson** [comment]
ok I'm stupid, it's `*:not(span){` . I probably thought of another programming lang.

Its working now
