### ISSUE TITLE
Cant build !!!

### ISSUE THREAD

**Issue by joreb** [fabiocolacio/Marker#185]
![marker](https://user-images.githubusercontent.com/37866574/38452198-f2aebf82-3a5c-11e8-95a3-0e2f5958557a.png)
error on attempting via both ninja and make  gtype not recognised 

![marker 2](https://user-images.githubusercontent.com/37866574/38452213-3b0b6c12-3a5d-11e8-91ca-628bcfe79041.png)

Marker-2018.03.09
also i am fairly new to Linux might be something stupid
please help thank you

**Comment by joreb** [comment]
Marker-2018.03.09

**Comment by fabiocolacio** [comment]
Hi @joreb,

You need gtk 3.20 or newer to run *Marker*. The errors you are getting indicate that you are using an older version of gtk (I believe Ubuntu 16.04 uses gtk 3.18).
