### ISSUE TITLE
Cant get charter to work

### ISSUE THREAD

**Issue by ronhasson** [fabiocolacio/Marker#187]
Even in the [test/markdown_test.md](https://github.com/fabiocolacio/Marker/blob/master/test/markdown_test.md) where the syntax is 100% correct and Charter is enabled in the settings, I get just an empty space. when Charter is disabled in the setting I can see just the syntax in a code box.

Mermaid works just fine.
Also, I can't see any script named charter in `usr/share/[marker folder]/scripts/`

Is there a dependency I need to install?

**Comment by ronhasson** [comment]
I got this:

`(marker:18107): GLib-GIO-CRITICAL **: 00:22:53.113: g_file_get_uri: assertion 'G_IS_FILE (file)' failed`

**Comment by fabiocolacio** [comment]
Interesting, that seems like it is an issue with Marker, rather than Scidown. Does this happen just when opening an existing file, or also when creating a new one?

I will see if I can reproduce this when I get the chance.

**Comment by ronhasson** [comment]
opening one

**Comment by Mandarancio** [comment]
I have always the following errors:

```

**Comment by fabiocolacio** [comment]
@Mandarancio the first error is most likely due to the gtk theme you are using. Sometimes i get warnings like this when using themes other than Adwaita.

**Comment by dasnoopy** [comment]
...same issue here on archlinux an using marker-git  compiled using the AUR package.

If could help,  at least for me,  `charter`  seems doesn't work also starting with a new file and as far as I remember  it never  worked before. E.g: 

1) start  marker 
2) pasted e.g. from test/markdown_test.md  only the `charter` code
3) a chart is never  visible  (related option is enabled)

A short explanation video:
![charter_issue](https://user-images.githubusercontent.com/296922/38464410-da7f68c4-3b0d-11e8-97a7-226d04d42606.gif)

Thanks
Andrea

**Comment by fabiocolacio** [comment]
I have not been able to reproduce any of the issues mentioned here. I don't have the failed assertion, and my charter is working fine.

I am running Marker from git master, and my OS is Fedora 27.

Perhaps the issue is caused from different versions of libraries for different distros?

**Comment by Mandarancio** [comment]
I have arch as well and I don't have any issue but I don't use the aur package, I will try to install the aur package and see what happen

**Comment by dasnoopy** [comment]
Hi.  I tried to compiled  `charter`  as standalone on my arch linux box... 
I create a  quick PKGBUILD  that produced and install following files
```
/usr/bin/charter_svg
/usr/bin/charter_tex
/usr/lib/libcharter.so
```

Then I create a simple `test` file copying code from the usual `markdown_test` file
```
title: a simple plot
x-axis:
  label: x
y-axis:
  label: y
plot:
  x range: -3 3 60
  y math: exp(-(x^2))
  label: gausian
```
Trying to execute following  command:
```
#charter_svg test 
```

but the output is a laconic:
```
</svg>
```

for the record, the command `#charter_tex test` produced, I think, the correct output:
```
\begin{tikzpicture}
\begin{axis}[
	grid=both,
	title={a simple plot},
	xlabel={x},
	ylabel={y},
]
\addplot[
	line width = 1.000000pt,
	solid,
...
...
```

Andrea

**Comment by SL315** [comment]
I am getting a similar issue on Solus from Git master.

In my case something is displayed, but incorrect and I think this might be related to localization.
Exporting the Marker file to HTML and opening the HTML file in Gedit shows, that the svg-data decimals are separated with ',' instead of '.' which is something typical for my german localization.

![screenshot1](https://user-images.githubusercontent.com/33317476/38577900-89b04d90-3d02-11e8-9c91-0e5967af25db.png)

Interestingly, using `charter_svg` with the charter-data puts the required decimal point and the chart is drawn correct.

![screenshot2](https://user-images.githubusercontent.com/33317476/38578084-2499c214-3d03-11e8-83b3-42b4c0e1c67a.png)

**Comment by Mandarancio** [comment]
@dasnoopy  Could you pass me your charter `PKGBUILD` file, as on my arch I"m not able to reproduce the issue with charter? Thank you!
@SL315 So this seems a problem of localization, I will try to understand where is produced! Thank you for your very useful report!

**Comment by Mandarancio** [comment]
I updated `charter` forcing to use the `en_US` locale when generating the `svg`, could you try it now?

**Comment by SL315** [comment]
Now it works in my case exactly as it should.

Thanks a lot for this.

**Comment by dasnoopy** [comment]
just an update: 
after  latest commits related to `localization` and `charter` **, I'm still not able to "see" chart** in `marker` nor using a standalone version of `charter`: same empty space in `marker` and same weird output using `charter_svg` , as reported above.
for the record, I installed both app using a PKGBUILD file

Then I did some test with  `marker` and `charter` **compiIing them from scratch and  magically charts appears** in `marker` and the `charter_svg `command produced the correct svg output

so the issue reported here I thinkc could be considered solved but apparently I'm having an issue with binary produced by the PKGBUILD: i'll try to do further test to undestand better what happens with PKGBUILD file

thanks 
Andrea

**Comment by Mandarancio** [comment]
@ronhasson could you confirm that using the last `marker` version compiled from git solve the `charter` problem for you as well?

**Comment by AlexTalker** [comment]
@Mandarancio @ronhasson I tried both(AUR git and release packages) but both doesn't render anything.
![2018-04-15-231515_902x639_scrot](https://user-images.githubusercontent.com/3531127/38783484-0cbc405a-4103-11e8-9274-120898ece465.png)
No error is produced to stdout/stderr either, except warnings related to GTK theme.
Seems strange to me, especially the fact that there's no separate AUR package for the library, so I could checkout it standalone.

**Comment by ronhasson** [comment]
a quick question, I didn't use meson and ninja before and I can't find a good tutorial. after I install this manually, how do I uninstall it and revert back to the AUR package / update the build manually?

**Comment by AlexTalker** [comment]
@Mandarancio okay, I tried this way but now it renders only axes.
Also, when I trying to print as PDF file, I get following error:
`print failed with error: Printer not found`
Which previously were only during exporting functionality. So, obviously, I cannot print markdown document to test if chart is drawn okay there.

**Comment by Mandarancio** [comment]
@ronhasson: `meson` is  a very easy build system (an alternative to `CMake`, `QMake` and many others) to use and install, is available in the `extra` repository of `Arch` and so you can easy install it via `pacman`, I find the [project page](http://mesonbuild.com/Tutorial.html) very complete and with simple tutorial.
To remove the installed package simply type: 
```bash
cd build/
sudo ninja uninstall
```

@AlexTalker: the `pdf` exporter for the moment is based on the `webkit2gtk` one, so if charter does not work on the live preview it will not work neather in the `pdf` version. Could you tell me which localisation are you using (e.g. en_UK, it_IT....) ?

**Comment by ronhasson** [comment]
yup, compiling directly from git solves this problem and issue #191

**Comment by AlexTalker** [comment]
@Mandarancio `ru_RU.UTF-8`

**Comment by fabiocolacio** [comment]
@mmetak, are you aware of these issues with the AUR version? Do you have any ideas of what could be causing these?

**Comment by mmetak** [comment]
@fabiocolacio  yes, I saw this issue and I can confirm it. The pkgbuild file is pretty simple and I also tried to build it with other flags to leave everything (enable debug , disable strip, etc.) and nothing made any difference.

When I install it manually and open test markdown page I get this at first.

![screenshot_20180416_202438](https://user-images.githubusercontent.com/6218030/38827818-6cd7c03e-41b4-11e8-97a6-f9a1bef6f73a.jpeg)

Then I go to preferences, click disable and again to enable charter and then it shows it like it should.
![screenshot_20180416_202517](https://user-images.githubusercontent.com/6218030/38827882-982b88ec-41b4-11e8-9f4d-fc46a9e78d9c.jpeg)

I really don't know. Could it still be something with the locale? (`sl_SI.UTF-8`) I still get:
```
not found: en_US
```

**Comment by AlexTalker** [comment]
@mmetak indeed, disabling/enabling works. Thanks.

**Comment by AlexTalker** [comment]
@Mandarancio Okay, I successfully build working package, code is here: https://gist.github.com/4563ebde05fc8159bdf77fae45f50745
But, problem with 're-enabling' the `charter` on each run is still exists. But I noticed this error(not warning, wow!):
```(marker:7185): Gtk-CRITICAL **: 20:58:09.724: gtk_combo_box_set_entry_text_column: assertion 'model == NULL || text_column < gtk_tree_model_get_n_columns (model)' failed
```
And this is the only text that printed on stdout/stderr now on test markdown file.

**Comment by mmetak** [comment]
Hey @fabiocolacio @Mandarancio 
After some fiddling I managed to narrow it down somewhere to linking charter.
The package needs to be built with `options=(!buildflags)` to successfully link charter in marker binary.
Otherwise there's no mention of charter in the binary.

Secondly, I also had to change `setlocale(LC_ALL, "en_US");` to `setlocale(LC_ALL, "C");` in https://github.com/Mandarancio/charter/blob/eec2077ac9a9b2333e2a9ec4170cf4f565a4f15d/src/svg.c#L709. This fixes the other issue that @AlexTalker also mentioned above where you need to disable/enable charter in preferences.

**Comment by mmetak** [comment]
Hi again @fabiocolacio @Mandarancio 
I don't think that is issue is fully fixed? Shouldn't the issue with charter I mentioned above be fixed in charter?
