### ISSUE TITLE
release tarball contains vcs history

### ISSUE THREAD

**Issue by bavier** [fabiocolacio/Marker#194]
The `Marker.2018.03.09.tar.xz` tarball is 54.6MiB large and contains 55.2 MiB of git history in the `.git` directory.  I can't imagine someone would want the history when downloading a release tarball.  Removing it would bring the download to about 5.4MiB.

Semi-related: there are build artifacts in `src/scidown/build` that maybe shouldn't be in a release tarball.

**Comment by Cogitri** [comment]
Also, there's no release tarball for 04.25 yet

**Comment by fabiocolacio** [comment]
Hi @bavier , I created a script ``archive.sh`` which creates archives automatically, and should solve this issue. Please check the archive in the latest release and let me kniw if it is acceptable. The download is still quite large, however, because we ship with MathJax, which is a large library.
