### ISSUE TITLE
I I have this error

### ISSUE THREAD

**Issue by libi1998** [fabiocolacio/Marker#197]
when I go to type the command _meson .. --prefix / usr_ I get this error. How can I solve [it?[](url)](url
![schermata da 2018-04-27 12-18-22](https://user-images.githubusercontent.com/25205064/39358065-1b4bc5ee-4a15-11e8-996b-03f4f23c1310.png)
)

**Comment by fabiocolacio** [comment]
@libi1998 did @r00sta's advice fix your problem?

**Comment by libi1998** [comment]
@fabiocolacio yes, thank you!
