### ISSUE TITLE
Inlcude scidown, charter and tinyexpr in realease download

### ISSUE THREAD

**Issue by r00sta** [fabiocolacio/Marker#198]
Would it be possible to include the scidown, charter and tinyexpr sources in the release tarball or is there a disadvantage/issue with doing this?

Sorry if this has been addressed already.

**Comment by fabiocolacio** [comment]
Because we are using submodules, the github releases that are automatically created do not include them. The latest release has another archive called ``marker.zip`` which i made sure has those dependencies. Please let me know if this is suitable.

**Comment by r00sta** [comment]
Hi, the marker.zip is ideal. Thanks.
