### ISSUE TITLE
Exporting/Printing doesn't seem to work

### ISSUE THREAD

**Issue by U2328** [fabiocolacio/Marker#201]
So as I was playing around with Marker I've stumbled upon an issue where I can't seem to export or print any given file; furthermore, it seems as though the location picker for the location of said export/_print_ (_print to pdf_ I mean) was fairly broken as it didn't let me properly choose a directory.
These are some of the errors I get when I launch Marker.
![selection_001](https://user-images.githubusercontent.com/30415153/39471461-9dac6616-4d43-11e8-9e10-8928f5b58424.png)
This is what the export looks like for me.
![selection_002](https://user-images.githubusercontent.com/30415153/39471465-9fdba172-4d43-11e8-84b4-0da8c8ac1d07.png)
There should be a `test.html`in there but I can't seem to find it...
![selection_003](https://user-images.githubusercontent.com/30415153/39471469-a28537a8-4d43-11e8-857a-c63ac9260fd5.png)
I'm running all this on Ubuntu 18.04 and installed it via flatpak.

**Comment by U2328** [comment]
I've checked the version and it is indeed 2018.04.27, and after the daily boot I checked it out again it still doesn't want work properly.

**Comment by s-slash** [comment]
Hi,
I got the same problem running ubuntu 16.04 and using the flatpak command but the location picker did not even find hidden directory
Export did not work for any format nether printing
I hope this will help, otherwise I can give more information on request

**Comment by fabiocolacio** [comment]
@U2328 @s-slash 

Have either of you used Marker on flatpak before ``2018.04.27``? If so was the error present in earlier versions?

**Comment by s-slash** [comment]
Yes I also used the 2018.03.09 version and same error

**Comment by jsparber** [comment]
As long we use [GtkFileChooserNative](https://developer.gnome.org/gtk3/stable/gtk3-GtkFileChooserNative.html) we don't need the access. The reason was that Marker doesn't need to have full home access since it opens only one file a time.

> When the application is running in a sandboxed environment without direct filesystem access (such as Flatpak), GtkFileChooserNative may call the proper APIs (portals) to let the user choose a file and make it available to the application.

**Comment by jsparber** [comment]
I just woke up, I didn't realize we are talking about the Printer dialog. It seams like a gtk bug. How do we create the Printer dialog?

**Comment by fabiocolacio** [comment]
Oh I see. It seems I was still using a normal GtkFileChooser for the export dialog, which is what was causing the exporting issue.

I will test more with the print dialog to see what's up.

**Comment by jsparber** [comment]
I filed a bug report in GTK https://gitlab.gnome.org/GNOME/gtk/issues/1068

**Comment by fabiocolacio** [comment]
I made a partial fix for this by using ``GtkFileChooserNative`` in the exporter dialog in this commit: https://github.com/fabiocolacio/Marker/commit/2a18702d9dbcab8fec6cd332cfed1be2ab339787 (not yet merged into master branch).

With that said, I believe we still need ``--filesystem=home``, because opening files from the command-line is still not permitted by the Flatpak version. @jsparber is there some workaround for this aside from using ``--filesystem=home``?

Furthermore, ``GtkFileChooserNative`` does not fully support ``GtkFileFilter``, which greatly hinders usability in my opinion.

**Comment by fabiocolacio** [comment]
I added filesystem access to the home folder which fixed this issue for me.

Please run ``flatpak update``, and test this out. If the issue persists, let me know in this thread.
