### ISSUE TITLE
Compatibility with KDE5?

### ISSUE THREAD

**Issue by NikoZHAI** [fabiocolacio/Marker#203]
Hello,

I just installed Marker but it doesn't seem to work on KUBUNTU 18.04 Bionic. When I try to start it, an error was raised: **KDEInit could not launch 'marker'**.

Keep this good work on and many thx in advance.

**Comment by fabiocolacio** [comment]
Hi @NikoZHAI 

Did you compile from source or use flathub. Also which version (git master, a release, etc) of marker did you install?

If you run marker from the terminal does it work?

**Comment by NikoZHAI** [comment]
Hi fabiocolacio!

I compiled a release tar from source. I tried again and everything just worked fine...
Thank u anyway for replying, and sorry for wasting your time...

Cheers
Niko

**Comment by fabiocolacio** [comment]
@NikoZHAI dont be sorry, all issues are welcome!
