### ISSUE TITLE
Marker not themed by GTK Theme

### ISSUE THREAD

**Issue by IronPiston** [fabiocolacio/Marker#204]
I currently have the Arc Theme installed using Gnome Tweak Tool, and it worked correctly on all applications except for Marker. I have tried switching themes, manually installing them, etc. I cannot change Marker from the default Adwaita theme, and I see nothing in the preferences that would fix this problem.

I just installed the latest version from the Flatpack

**Comment by IronPiston** [comment]
I just installed from source, and the issue no longer occurs

**Comment by SebastJava** [comment]
Confirmed.
