### ISSUE TITLE
Save / Save As do not work

### ISSUE THREAD

**Issue by Magicloud** [fabiocolacio/Marker#206]
Flatpak distribution. Ubuntu Bionic.

Clicking Save button, or Save As menuitem does nothing. The title of the window is still `*Untitled.md`.

**Comment by U2328** [comment]
This may relate to the issue I opened up earlier: #201.
Could you try the stuff I've listed there and check if the same stuff happens to you?

**Comment by Magicloud** [comment]
@U2328 Thanks. I did not see "save" in your thread, but "export" is kind of worse. Nothing showed at all.
![screenshot from 2018-05-17 10-47-35](https://user-images.githubusercontent.com/1886157/40154199-c60a99ec-59bf-11e8-99e8-c36352cccf08.png)

**Comment by fabiocolacio** [comment]
@Magicloud  are the save and save-as shortcuts (``Ctrl``+``s`` and ``Ctrl``+``Shift``+``s``) also broken for you, or is it just the menu?

**Comment by fabiocolacio** [comment]
@U2328 are you able to reproduce this save and save-as bug?

**Comment by Magicloud** [comment]
Shortcuts do not seem working.

**Comment by fabiocolacio** [comment]
@Magicloud can you update to the latest version with ``flatpak update``, and tell me if this issue was solved for you?

I resolved #201 and this may be related.

**Comment by Magicloud** [comment]
Seems working. Thanks.
