### ISSUE TITLE
What GTK/Shell theme are you using in "scrot.png"

### ISSUE THREAD

**Issue by bkdogan** [fabiocolacio/Marker#207]
Hi there, can tell me what theme you are using in the file "scrot.png"? It looks really nice. 

Keep up the great work!

**Comment by fabiocolacio** [comment]
Hi @bkdogan 

I am using one of the light variants of [vimix](https://github.com/vinceliuice/vimix-gtk-themes) in that screenshot (for the shell and the widgets). My personal favorite is Vimix-Light-Ruby.

**Comment by bkdogan** [comment]
Thank you! :smile:

**Comment by fabiocolacio** [comment]
Yep, anytime!
