### ISSUE TITLE
Loses Latex rendering after saving to .md file

### ISSUE THREAD

**Issue by MeisterGig** [fabiocolacio/Marker#212]
Hello,
when i save my work to a .md file it suddenly losses all of it's Latex code and Pictures
It looks like this in the Preview:
\(~~~~ L_F (M_1) = \{ a^n b^n c^n | n \in \mathbb{N}_0 \}\)
What do i do to fix this?

**Comment by fabiocolacio** [comment]
Did you sve the file with a filename that has special characters? If so, this may be the same issue as #136
