### ISSUE TITLE
meson.build:75:0: ERROR:  Native dependency 'gtkspell3-3.0' not found

### ISSUE THREAD

**Issue by Fr4nci** [fabiocolacio/Marker#214]
Hi to everybody,

I already thank who will help me. `I` have a problem in the installation of Marker (here is the output)

`$ meson .. --prefix /usr
The Meson build system
Version: 0.46.1
Source dir: /root/Marker
Build dir: /root/Marker/build
Build type: native build
Project name: Marker
Native C compiler: cc (gcc 7.3.0 "cc (Debian 7.3.0-21) 7.3.0")
Build machine cpu family: x86_64
Build machine cpu: x86_64
Found pkg-config: /usr/bin/pkg-config (0.29)
Native dependency glib-2.0 found: YES 2.56.1
Native dependency gtk+-3.0 found: YES 3.22.29
Native dependency glib-2.0 found: YES 2.56.1
Native dependency gtksourceview-3.0 found: YES 3.24.7
Native dependency webkit2gtk-4.0 found: YES 2.20.3

meson.build:75:0: ERROR:  Native dependency 'gtkspell3-3.0' not found

A full log can be found at /root/Marker/build/meson-logs/meson-log.txt`

The problem is in the fact that gtkspell3 -3.0 are already installed

**Comment by fabiocolacio** [comment]
Hi @Fr4nci it is possible that you have the gtkspell runtime, but not the development headers.

In your package manager there is likely a ``gtkspell3-3.0``  package, as well as a ``gtkspell3-3.0-devel``. You will need the one labeled ``devel``. The exact name of the package you need varies by distro.

**Comment by Fr4nci** [comment]
@fabiocolacio I install many packages and i have install the rpm file ( and convert it in .deb) from other distro but nothing

**Comment by gitfineon** [comment]
Hi @Fr4nci ,
did this solve your issue? Then please close it. As @fabiocolacio mentioned, not only gtkspell3-3.0 library have to be installed, also the developer package to build the application.

I've installed it on Ubuntu 18.04 and it works fine. Can you please append the following to the README? This would make it a lot easier to quickly install all required packages on debian-based distros.
```
sudo apt install meson pkg-config libgtk-3-dev libgtksourceview-3.0-dev libwebkit2gtk-4.0-dev libgtkspell3-3-dev
```
