### ISSUE TITLE
Essential feature request.

### ISSUE THREAD

**Issue by tnilzon** [fabiocolacio/Marker#221]
This editor really outshines all other editors I have tried, except on one major feature: The option to **synchronize scrolling in 'Editor' and 'Preview' pane/window**. I think this is of most importance and should be given a high priority on the "New Feature" list.

I also like that Marker is designed with the Gnome desktop in mind (the best I have seen).

Thanks for a great editor!
/ tnilzon

**Comment by fabiocolacio** [comment]
I really like this idea, and I have an issue for it already at #14. I am closing this for consolidation.
