### ISSUE TITLE
Hotkeys depend on keyboard layout

### ISSUE THREAD

**Issue by Exalm** [fabiocolacio/Marker#229]
If a keyboard layout uses different keys, hotkeys would be different or outright unavailable.

For example, Ctrl+S doesn't work with cyrillic layouts.

**Comment by fabiocolacio** [comment]
I think i can fix this by using accelerators rather than listening to gdk events (which was on the roadmap anyways). A fix should be coming soon for this.

**Comment by Exalm** [comment]
Yes, it works :)
