### ISSUE TITLE
Must Marker check if a url is valid?

### ISSUE THREAD

**Issue by jsparber** [fabiocolacio/Marker#231]
Marker currently checks if a link inserted into markdown is valid, which causes an error in flatpak because Marker doesn't have network access. See the related  [issue](https://github.com/flathub/com.github.fabiocolacio.marker/issues/13)

Could we remove the check?

**Comment by fabiocolacio** [comment]
Marker does not check if the url is valid, it just calls ``gtk_show_uri_on_window()``.

Perhaps it is checked either by webkit, or by gtk, but it is never checked by Marker.

Here is the relevant function:

```
static gboolean
open_uri (WebKitPolicyDecision *decision) {
  WebKitResponsePolicyDecision* policy_decision = WEBKIT_RESPONSE_POLICY_DECISION(decision);
  const gchar * uri = webkit_uri_request_get_uri(webkit_response_policy_decision_get_request(policy_decision));
  GtkApplication * app = marker_get_app();
  GList* windows = gtk_application_get_windows(app);
  time_t now = time(0);
  gtk_show_uri_on_window (windows->data, uri, now, NULL);
  webkit_policy_decision_ignore(decision);
  return TRUE;
}
```

**Comment by jsparber** [comment]
The docs say gtk_show_uri_on_window() is the recommended way for use in sandboxes, I also looked at the code in gtk and it doens't look like it making any network requests. I guess Webkit checks the url.

**Comment by jsparber** [comment]
I think i found the reason why we need network access:
Marker caches a  WEBKIT_POLICY_DECISION_TYPE_RESPONSE to cancel the request and open the link in the default browser, but this makes first a connection to the resource. I think we could use WEBKIT_POLICY_DECISION_TYPE_NAVIGATION_ACTION to catch requests made to http resources and open them directly in the browser.

https://github.com/fabiocolacio/Marker/blob/master/src/marker-preview.c#L88
