### ISSUE TITLE
(Do not) use GNOME appmenu depending on the DE 

### ISSUE THREAD

**Issue by maoschanz** [fabiocolacio/Marker#233]
with `gtk_application_prefers_appmenu` it's possible to know it the user want an appmenu without adding a setting

----

This is not an issue i actually ask you to fix, actually i've a patch on my disk rn i'll commit it maybe tomorrow, i just want to mention an issue in the commit

**Comment by Exalm** [comment]
Is it needed considering GNOME is moving away from appmenu as well? https://gitlab.gnome.org/GNOME/Initiatives/wikis/App-Menu-Retirement

**Comment by Exalm** [comment]
Actually, true, I think the new GNOME versions will just answer false and it will just work \o/

On another note, I've updated the hamburger layout with this option disabled to match the initiative.
