### ISSUE TITLE
New app icon

### ISSUE THREAD

**Issue by bertob** [fabiocolacio/Marker#243]
Hi, Tobias from the GNOME design team here. We're updating the icon guidelines this cycle, so I'm reaching out to ask if you'd be interested in a new icon.

Here's what we currently have:

![image](https://user-images.githubusercontent.com/1908896/46872559-c1cf2700-ce34-11e8-9aaa-fb08c4a50c83.png)

More information on the initiative here: https://gitlab.gnome.org/GNOME/Initiatives/issues/2

**Comment by fabiocolacio** [comment]
Hi @bertob,

I think the new icon looks fantastic! I made the former one myself, but I am not very talented when it comes to this kind of thing, so any improvements are welcome!

Please feel free to make a PR with the new icon, or if there is something I can do to help, let me know. Whenever the icon is ready, I'd also like to know the name of the artist(s) as well so I can give them proper credit.
