### ISSUE TITLE
Marker does not render labeled LaTeX equations with MathJax

### ISSUE THREAD

**Issue by N0rbert** [fabiocolacio/Marker#247]
Below are examples of the Markdown document with LaTeX equation:

1. Labeled equation with `\label{}`:

```
\begin{equation}
  g\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
\label{binom2}
\end{equation}
```

2. Labeled equation with RMarkdown + bookdown syntax (see [this chapter](https://bookdown.org/yihui/bookdown/markdown-extensions-by-bookdown.html#equations)):

```
\begin{equation} 
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation} 
```

I have enabled _Render Math: MathJax_ support, but both equations do not render on Marker 2018.07.03.
Please allow their rendering.

**Comment by fabiocolacio** [comment]
![Screenshot from 2019-05-04 20-57-36](https://user-images.githubusercontent.com/5248352/57188198-72734580-6eaf-11e9-9b58-05168ddbbd2d.png)

It is rendering on my machine (compiled from source on Arch)! How did you install Marker and on what OS?

I don't believe scidown renders labels though. Please refer to the info [here](https://github.com/mandarancio/scidown) about scidown.

You can add a caption by making it a figure:
![Screenshot from 2019-05-04 21-05-44](https://user-images.githubusercontent.com/5248352/57188259-73f13d80-6eb0-11e9-9aaf-24d4abec6aca.png)

**Comment by N0rbert** [comment]
I planned to avoid `$$` in the equation declaration.
I understood that this functionality is driven by _scidown_.
So current issue may be closed here.

Thank you! The overall functionality of Marker looks great!

**Comment by N0rbert** [comment]
But I have small question - do you use local copy of MathJax or you download it on the fly?
For example, Retext markdown editor download MathJax javascripts on the fly and show labeled equations normally:
![retext](https://user-images.githubusercontent.com/309456/57190657-7fcb1700-6f25-11e9-8527-973ede4bdaf9.png)

Is it possible to adjust MathJax settings on Marker side?

**Comment by N0rbert** [comment]
I compared the HTML output of ReText with Marker.

ReText has the following representation of equations:

```
<p>
<script type="math/tex; mode=display">\begin{equation}
  g\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
\label{binom2}
\end{equation}</script>
</p>

<p>
<script type="math/tex; mode=display">\begin{equation}
  f\left(k\right) = \binom{n}{k} p^k\left(1-p\right)^{n-k}
  (\#eq:binom)
\end{equation}</script>
</p>
```
and they can be rendered by MathJax.

While Marker converts them to plain text (or simply ignores them):

```
<p>\begin{equation}
  g\left(k\right) = \binom{n}{k} p<sup>k\left(1-p\right)<sup>{n-k}</sup></sup>
\label{binom2}
\end{equation}</p>

<p>\begin{equation}
  f\left(k\right) = \binom{n}{k} p<sup>k\left(1-p\right)<sup>{n-k}</sup></sup>
  (#eq:binom)
\end{equation}</p>
```
and they get ignored by MathJax.

Could you please change the Marker behavior with such equation syntax to act as ReText does?

**Comment by N0rbert** [comment]
Bug exists in Marker 2020.04.04 with MathJax selected to show math.

**Comment by fabiocolacio** [comment]
To answer your earlier question, Marker has a local installation of mathjax to keep it working offline and to reduce security risks.

The HTML conversion is handeled by scidown, not Marker. This bug should be on the scidown repository.
