### ISSUE TITLE
Fedora RPM package

### ISSUE THREAD

**Issue by tim77** [fabiocolacio/Marker#255]
#### Not issue, just info:

📦 Marker RPM package in [COPR](https://copr.fedorainfracloud.org/coprs/atim/marker/)

#### How to install:
```shell
sudo dnf copr enable atim/marker -y && sudo dnf install marker -y
```
#### Run:
```
marker
```
Thank you for this app. I would like to have it in official repos, but this in not possible because using git submodule during build process not allowed in Fedora.

**Comment by fabiocolacio** [comment]
Thank you @tim77! I will update the README with these instructions.
