### ISSUE TITLE
6th Level Notes aren't readable in Preview

### ISSUE THREAD

**Issue by Severus157** [fabiocolacio/Marker#257]
Hello,

Just having a little Problem with the Preview Window, the Notes in the 6th Level aren't readable there. It can be shown by other Document Viewers, I tried Okular.

Marker Version: 2018.04.27 shown in Preferences (Newest AUR)
![Marker_6th_Level](https://user-images.githubusercontent.com/9520379/55683002-f67eef80-593a-11e9-9b4c-de1274105e00.png)

**Comment by fabiocolacio** [comment]
Hi @Severus157, this would be an issue with the parser. This issue should go to the [scidown repo](https://github.com/mandarancio/scidown)
