### ISSUE TITLE
Unable to install Marker on Fedora 30

### ISSUE THREAD

**Issue by snydox** [fabiocolacio/Marker#266]
I'm trying to install Marker from Flathub. THe installation takes a long time, and it never completes. I tried using the Software Centre but that didn't work. So I tried command line and got the following error:

[snydox@localhost ~]$ flatpak install flathub com.github.fabiocolacio.marker
Looking for matches…

com.github.fabiocolacio.marker permissions:
    ipc                   wayland       x11       file access [1]
    dbus access [2]

    [1] home, xdg-run/dconf, ~/.config/dconf:ro
    [2] ca.desrt.dconf

        ID                                    Arch   Branch Remote  Download
 1. [✗] com.github.fabiocolacio.marker        x86_64 stable flathub     9.8 MB / 27.4 MB
 2. [ ] com.github.fabiocolacio.marker.Locale x86_64 stable flathub < 234.7 kB (partial)

Error: While pulling app/com.github.fabiocolacio.marker/x86_64/stable from remote flathub: Server returned HTTP 503
error: Failed to install com.github.fabiocolacio.marker: While pulling app/com.github.fabiocolacio.marker/x86_64/stable from remote flathub: Server returned HTTP 503

**Comment by wctaylor** [comment]
I have also struggled with installing the Marker flatpak on Fedora 30. However, after many failed attempts with the HTTP 503 error, I have had it succeed. I've uninstalled and reinstalled a few times, and I'd say roughly 1 in 10 attempts will actually complete the install.

**Comment by fabiocolacio** [comment]
This sounds like an issue with the flathub servers or possibly your installation of flatpak/fedora. In any case, it is not related to the Marker code itself, and is out of my control.
