### ISSUE TITLE
Syntax Highlighting

### ISSUE THREAD

**Issue by LiohMoeller** [fabiocolacio/Marker#268]
On the screenshots the Markdown Text has some kind of syntax highlighting in Editor mode. E.g. Headings are displayed in green and Bold Text in red.

I have installed Marker from Flathub and have not found a way to enable this kind of Markdown Syntax Highlighting.

**Comment by fabiocolacio** [comment]
You must check this box in the preferences:

![Screenshot from 2020-07-25 00-02-28](https://user-images.githubusercontent.com/5248352/88451286-47ee0f00-ce0a-11ea-8ced-68a7636e873a.png)
