### ISSUE TITLE
Flatpak Marker can't render images on the internet

### ISSUE THREAD

**Issue by Lin-Buo-Ren** [fabiocolacio/Marker#275]
![Screenshot](https://user-images.githubusercontent.com/13408130/62009458-1a886a00-b192-11e9-82cb-d70781dbbe9a.png)

My two cents is that the Flatpak packaging doesn't have the network permission, which relates to [Enable network access by Kekun · Pull Request #14 · flathub/com.github.fabiocolacio.marker](https://github.com/flathub/com.github.fabiocolacio.marker/pull/14)

**Comment by Mandarancio** [comment]
Hi Thanks for the tip! I don't know who made the flatpack, maybe @fabiocolacio  knows?

**Comment by Mandarancio** [comment]
It seems that now it does not render also the local images #287

**Comment by Esokrates** [comment]
This is fixed now in the flatpak, this report can be closed. It seems @Mandarancio is quite busy atm so @Lin-Buo-Ren could you please close the bug?

**Comment by Lin-Buo-Ren** [comment]
> This is fixed now in the flatpak, this report can be closed. It seems @Mandarancio is quite busy atm so @Lin-Buo-Ren could you please close the bug?

Sure.  Thanks for the help.
