### ISSUE TITLE
Preview scrollbar auto-resetting to top 

### ISSUE THREAD

**Issue by nluizsoliveira** [fabiocolacio/Marker#276]
I'm not sure if it's a bug, miss-configuring of mine or the way the app is supposed to work. But it's making live-previewing impossible. Every typing on the "code"  window pushes the preview window's scrollbar to the very top, which doesn't allow to see how the bottom-content of the document is being rendered

**Comment by Mandarancio** [comment]
Hi, sorry for the late answer, I am now working on it and I commited a temporary fix that looking promising. The only problem that on my system I could see the page quickly scrolling to the correct position after every updates... 

I am working on it!

**Comment by Mandarancio** [comment]
Now on my machine is fixed and working fine using the scroll-extension.
Note: the plugin must be installed and so you need to run `sudo ninja install` once compiled.
