### ISSUE TITLE
Question: How to open sketch editor

### ISSUE THREAD

**Issue by Esokrates** [fabiocolacio/Marker#285]
I can't figure out how to get into the sketch editor, could you outline how that is done? Using latest flatpak package.

**Comment by Mandarancio** [comment]
Normally the short cut is `ctrl+d` I hope it works on the flatpack version

**Comment by Esokrates** [comment]
Ah, Thanks, it works in the flatpak version. Maybe you could make that more discoverable? Suggestion: Add an option in the right click menu "Insert sketch ...".

**Comment by Mandarancio** [comment]
Hi,
I will consider to add a right click menu.
However now if you click the menu item `keyboard shortcuts`:
![Screenshot from 2019-10-15 14-36-52](https://user-images.githubusercontent.com/276686/66832061-5b09af80-ef59-11e9-8455-f0e63a055a03.png)

You should have a dialogue showing all the shortcuts and functionalities available:
![Screenshot from 2019-10-15 14-37-14](https://user-images.githubusercontent.com/276686/66832064-5cd37300-ef59-11e9-9126-5824af13465c.png)
