### ISSUE TITLE
Enhancement: Provide deb-release file

### ISSUE THREAD

**Issue by DarkTrick** [fabiocolacio/Marker#288]
1. The dependencies listed cannot be found on ubuntu
2. Even though gtkspell3-3.0 is installed, meson tells it's not installed

You probably need to know a lot more about packages to be able to build Marker. 

Suggestion:
Provide a deb package for all ubuntu users. 

Reason:
- Installation possible
- uninstall possible

**Comment by Esokrates** [comment]
@DarkTrick Which Ubuntu version did you try this in? It worked just fine for me in Ubuntu 19.04.

Note that you can just install the flatpak in Ubuntu Software Center (just make sure you install `flatpak` and `gnome-software-plugin-flatpak` beforehand).

**Comment by Esokrates** [comment]
@DarkTrick Which Ubuntu version did you try this in? It worked just fine for me in Ubuntu 19.04.

Note that you can just install the flatpak in Ubuntu Software Center (just make sure you install `flatpak` and `gnome-software-plugin-flatpak` beforehand).
