### ISSUE TITLE
Release source files cannot be build -missing submodules code.

### ISSUE THREAD

**Issue by mobinmob** [fabiocolacio/Marker#290]
The zip and tar.gr files for the current release (2019.11.06) do not include the source for submodules. That means that the release archives cannot build as the documentation proposes.

**Comment by Mandarancio** [comment]
Ops, I am very sorry, I thought that github will automatically add the submodules.. I will add it tomorrow morning.

**Comment by Mandarancio** [comment]
I uploaded 2 new archives containing all sources.

**Comment by mobinmob** [comment]
Thank you, the new archives build fine. Ι sent a PR to update the package in voidlinux: (https://github.com/void-linux/void-packages/pull/17168).
