### ISSUE TITLE
Missing Menu with Flatpak on Fedora 30

### ISSUE THREAD

**Issue by wctaylor** [fabiocolacio/Marker#292]
The menu which allows one to access preferences doesn't appear in Fedora 30 via Flatpak. This menu does appear on a Pop!_OS system also running Marker through Flatpak.

If using a dark system them, one is stuck with issue #195 and no way to change it, which doesn't leave the best first impression. 

# Fedora 30
![Screenshot from 2019-12-13 09-19-26](https://user-images.githubusercontent.com/8593481/70806611-b86b8280-1d89-11ea-8c1a-2e4c40032b86.png)

# Pop!_OS 19.10
![image](https://user-images.githubusercontent.com/8593481/70806508-82c69980-1d89-11ea-8e44-4c5900ae294c.png)

**Comment by wctaylor** [comment]
Well, the menu shows up with Fedora 31. I'm not sure what may be missing with Fedora 30, but at least one can resolve it by updating.

**Comment by Mandarancio** [comment]
So I consider it closed thank you! :+1:

**Comment by mrjohnson22** [comment]
Looks like this isn't fully fixed. I'm using the Flatpak on Fedora 31 and no menu button appears:
![markerNoMenu](https://user-images.githubusercontent.com/8988672/75102640-e1e03000-55bc-11ea-8481-6dba97bb0c05.png)

No options appear in the desktop menu either:
![markerDesktopMenu](https://user-images.githubusercontent.com/8988672/75102646-050adf80-55bd-11ea-9b0e-37522a1fe3b9.png)
