### ISSUE TITLE
libscroll-extension.so

### ISSUE THREAD

**Issue by tim77** [fabiocolacio/Marker#293]
Hello. Some linters consider this error:

```
E: arch-dependent-file-in-usr-share /usr/share/com.github.fabiocolacio.marker/extensions/libscroll-extension.so
E: library-not-linked-against-libc /usr/share/com.github.fabiocolacio.marker/extensions/libscroll-extension.so
```

Why `libscroll-extension.so` installed in this location? How we can make our linters happier?

**Comment by krop** [comment]
Now that we have an openSUSE package, this is also considered bad for us.

```
[  991s] marker.x86_64: E: arch-dependent-file-in-usr-share (Badness: 590) /usr/share/com.github.fabiocolacio.marker/extensions/libscroll-extension.so
[  991s] This package installs an ELF binary in the /usr/share  hierarchy, which is
[  991s] reserved for architecture-independent files.
```

**Comment by DeadMozay** [comment]
Also, the library must have `soversion`, `*.so` this is a development library

**Comment by DeadMozay** [comment]
Also, the library must have soversion, *.so this is a development library

**Comment by mobinmob** [comment]
> Hello. Some linters consider this error:
> 
> ```
> E: arch-dependent-file-in-usr-share /usr/share/com.github.fabiocolacio.marker/extensions/libscroll-extension.so
> E: library-not-linked-against-libc /usr/share/com.github.fabiocolacio.marker/extensions/libscroll-extension.so
> ```
> 
> Why `libscroll-extension.so` installed in this location? How we can make our linters happier?

I encountered the problem in voidlinux, I solved it by patching meson.build:
https://github.com/void-linux/void-packages/blob/6e9ceae5a9a1e35ef75bfa16cabc56b6ffe89e76/srcpkgs/Marker/patches/elf_files_in_lib.patch
