### ISSUE TITLE
Merge efforts with Apostrophe

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#320]
The guys behind the project [Apostrophe](
https://gitlab.gnome.org/somas/apostrophe) are doing (IMHO) a great work and I believe they are supported directly by the Gnome team.

It could be interesting merge the efforts and work together. 

What do you think?

**Comment by fabiocolacio** [comment]
I have not heard of this one but it seems like a great project!

I don't plan to completely abandon Marker at the moment, but I will certainly keep tabs on Apostrophe and submit some PRs from time to time :)
