### ISSUE TITLE
can't resize left pane (editor)

### ISSUE THREAD

**Issue by Lvceo** [fabiocolacio/Marker#327]
can't resize left pane (editor) and get it larger for a better edition. The middle bar between pane should provide a moving option to enlarge the left pane.

**Comment by Mandarancio** [comment]
Hi @Lvceo, do you still have the issue? I can not reproduce it on the current dev version, which version are you using?

**Comment by Lvceo** [comment]
Hi @Mandarancio , I've just checked again with V2020.04.04, and now it works fine. It was probably a problem coming from an older version I was using.
Thanks again for checking.
