### ISSUE TITLE
Edit/add themes.

### ISSUE THREAD

**Issue by andreluisos** [fabiocolacio/Marker#338]
It's not a bug and maybe it shouldn't be asked here.

I'm using the Flatpak version.

I loved the app and I was wondering if it is possible to edit Is there a way to add css themes or edit the existing ones.

Thank you!

**Comment by henrique-andrade** [comment]
> It's not a bug and maybe it shouldn't be asked here.
> 
> I'm using the Flatpak version.
> 
> I loved the app and I was wondering if it is possible to edit Is there a way to add css themes or edit the existing ones.
> 
> Thank you!

If someone still has this doubt... I just found where to save CSS themes to use in the flatpak version of Marker:

`~/.local/share/flatpak/app/com.github.fabiocolacio.marker/current/active/files/share/com.github.fabiocolacio.marker/styles`

**Comment by LifeWatcher123** [comment]
> > It's not a bug and maybe it shouldn't be asked here.
> > I'm using the Flatpak version.
> > I loved the app and I was wondering if it is possible to edit Is there a way to add css themes or edit the existing ones.
> > Thank you!
> 
> If someone still has this doubt... I just found where to save CSS themes to use in the flatpak version of Marker:
> 
> `~/.local/share/flatpak/app/com.github.fabiocolacio.marker/current/active/files/share/com.github.fabiocolacio.marker/styles`

In my Fedora 35 Flatpak installation, this folder doesn't exist (the ~/.local/share/flatpak/app folder doesn't exist). Creating the folder and placing CSS styles there also doesn't work. Where else can custom CSS styles be placed?
