### ISSUE TITLE
Ukrainian translation for Marker

### ISSUE THREAD

**Issue by vlisivka** [fabiocolacio/Marker#346]
See in attachment.
[Marker.tar.gz](https://github.com/fabiocolacio/Marker/files/6143600/Marker.tar.gz)

**Comment by Mandarancio** [comment]
Hi @vlisivka , your work is great however it would be even better if you could fork Marker add the translation and then make a pull request (in this way your contribution will be easier to track as well).
For example @eson57 made like this to add the Swedish translation (https://github.com/fabiocolacio/Marker/pull/347).

**Comment by vlisivka** [comment]
Pull request is created.

**Comment by Mandarancio** [comment]
Merged thank you!
