### ISSUE TITLE
Problem with installation

### ISSUE THREAD

**Issue by cesar237** [fabiocolacio/Marker#358]
I'm on Ubuntu 20.04 and I wanted to install Marker. When I follow the instructions on the README, all steps are good but the last one.When running it, there is a msgfmt error. It tries to access the file /Marker/help/uk/uk.po, but it does not exist.
There is a snapshot :

<pre>Running custom install script &apos;/usr/bin/meson --internal yelphelper install --subdir=help --id=Marker --installdir=share/help --sources=index.page@@introduction.page@@pictures.page@@complex-data.page@@settings.page@@legal.xml --symlinks=true --media=figures/icon.png@@figures/scrot.png@@figures/scrot1.png@@figures/scrot2.png@@figures/sketcher.png&apos;
msgfmt: Erreur lors de l&apos;ouverture de « /home/cesar/Marker/help/uk/uk.po » en lecture: Aucun fichier ou dossier de ce type
Traceback (most recent call last):
  File &quot;/usr/bin/meson&quot;, line 20, in &lt;module&gt;
    sys.exit(mesonmain.main())
  File &quot;/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py&quot;, line 226, in main
    return run(sys.argv[1:], launcher)
  File &quot;/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py&quot;, line 215, in run
    return run_script_command(args[1], args[2:])
  File &quot;/usr/lib/python3/dist-packages/mesonbuild/mesonmain.py&quot;, line 163, in run_script_command
    return module.run(script_args)
  File &quot;/usr/lib/python3/dist-packages/mesonbuild/scripts/yelphelper.py&quot;, line 130, in run
    merge_translations(build_subdir, abs_sources, langs)
  File &quot;/usr/lib/python3/dist-packages/mesonbuild/scripts/yelphelper.py&quot;, line 57, in merge_translations
    subprocess.call([
  File &quot;/usr/lib/python3.9/subprocess.py&quot;, line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File &quot;/usr/lib/python3.9/subprocess.py&quot;, line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File &quot;/usr/lib/python3.9/subprocess.py&quot;, line 1821, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: &apos;itstool&apos;
<font color="#CC0000">FAILED: </font>meson-install 
/usr/bin/meson install --no-rebuild
ninja: build stopped: subcommand failed.
</pre>

**Comment by yochananmarqos** [comment]
> FileNotFoundError: [Errno 2] No such file or directory: 'itstool'

Same deal with the `marker-git` AUR package.  Apparently `itstool` is a missing build dependency, however it still fails with it:

```
Running custom install script '/usr/bin/meson --internal yelphelper install --subdir=help --id=Marker --installdir=share/help --sources=index.page@@introduction.page@@pictures.page@@complex-data.page@@settings.page@@legal.xml --symlinks=true --media=figures/icon.png@@figures/scrot.png@@figures/scrot1.png@@figures/scrot2.png@@figures/sketcher.png'
--- stdout ---
Installing /build/marker-git/src/build/help/uk/index.page to /build/marker-git/pkg/marker-git/usr/share/help/uk/Marker/index.page

--- stderr ---
msgfmt: error while opening "/build/marker-git/src/Marker/help/uk/uk.po" for reading: No such file or directory
Error: cannot open mo file /build/marker-git/src/build/help/uk/uk.gmo
Traceback (most recent call last):
  File "/usr/bin/meson", line 33, in <module>
    sys.exit(load_entry_point('meson==0.60.2', 'console_scripts', 'meson')())
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 235, in main
    return run(sys.argv[1:], launcher)
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 224, in run
    return run_script_command(args[1], args[2:])
  File "/usr/lib/python3.9/site-packages/mesonbuild/mesonmain.py", line 172, in run_script_command
    return module.run(script_args)
  File "/usr/lib/python3.9/site-packages/mesonbuild/scripts/yelphelper.py", line 131, in run
    install_help(src_subdir, build_subdir, sources, media, langs, install_dir,
  File "/usr/lib/python3.9/site-packages/mesonbuild/scripts/yelphelper.py", line 72, in install_help
    shutil.copy2(infile, outfile)
  File "/usr/lib/python3.9/shutil.py", line 444, in copy2
    copyfile(src, dst, follow_symlinks=follow_symlinks)
  File "/usr/lib/python3.9/shutil.py", line 264, in copyfile
    with open(src, 'rb') as fsrc:
FileNotFoundError: [Errno 2] No such file or directory: '/build/marker-git/src/build/help/uk/index.page'

FAILED: install script '/usr/bin/meson --internal yelphelper install --subdir=help --id=Marker --installdir=share/help --sources=index.page@@introduction.page@@pictures.page@@complex-data.page@@settings.page@@legal.xml --symlinks=true --media=figures/icon.png@@figures/scrot.png@@figures/scrot1.png@@figures/scrot2.png@@figures/sketcher.png' exit code 1, stopped
```

**Comment by ParkSeungwon** [comment]
uk.po file is located at root/po directory. 
change build.ninja file accordingly.(line 67, 68)

**Comment by yochananmarqos** [comment]
I just ended up symlinking `uk.po` from the po folder to the help folder.

**Comment by apandada1** [comment]
@ParkSeungwon  @yochananmarqos  Any idea why this error happens only for uk.po but not for other .po files?
