### ISSUE TITLE
Snap package ready 

### ISSUE THREAD

**Issue by soumyaDghosh** [fabiocolacio/Marker#402]
Hi, I have created a snap package for your app, and it's already in the snap-store working fine. Would you like to add this option as an official or unofficial package? Currently it has 128 active users.

```
[![Get it from the Snap Store](https://snapcraft.io/static/images/badges/en/snap-store-black.svg)](https://snapcraft.io/marker)
```

This the tag to publicise it

**Comment by Mandarancio** [comment]
Thank you very much, link added to the readme in the package section
