### ISSUE TITLE
Use webkit2gtk instead of webkitgtk

### ISSUE THREAD

**Issue by progandy** [fabiocolacio/Marker#42]
webkit(1)gtk is deprecated and at least arch linux doesn't even provide a compiled package anymore.
webkit2gtk seems to be the future and should be easy to use in marker:

```webkit_web_view_load_html``` instead of ...load_string
```webkit_web_view_is_loading``` instead of ...load_status
different parameters for ```web_view_context_menu```

**Comment by fabiocolacio** [comment]
Thanks for the heads up! Ill look into making the switch soon.

**Comment by fabiocolacio** [comment]
I have made the switch to webkit2gtk in the rewrite branch, which will be merged for the next release.
