### ISSUE TITLE
Change fonts?

### ISSUE THREAD

**Issue by VirgiliusHaufniensis** [fabiocolacio/Marker#44]
Hi

This app seems very promising. But am I missing something or is it impossible to configure the fonts? It stays the same regardless of how I've set the Gnome fonts in gnome-tweak-tool 
![skaermbillede fra 2017-10-24 06-31-06](https://user-images.githubusercontent.com/26080212/31924911-0e52ebe6-b885-11e7-9cae-85d8873451ef.png)

**Comment by fabiocolacio** [comment]
Thanks for the info. I have fixed the issue in the latest commit (tested under GNOME 3.26). It still requires further testing under non-gnome desktops though, as it looks for the gnome-shell's gsettings info, and takes the system font from there (this is the same behavior used by Gedit), and might cause crashes if gnome-shell can't be found.

**Comment by fabiocolacio** [comment]
I have tested it on a fresh install of a kde distro, and it works with no issues.
