### ISSUE TITLE
Improve the interface for working with multiple documents

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#47]

**Comment by fabiocolacio** [comment]
We need a tabbed interface or some kind of tree sidebar implemented

**Comment by fabiocolacio** [comment]
@Mandarancio what do you think is the best way to handle this?

Tabs are the first thing that come to mind, but they wouldn't work very well when editing a lot of documents at once.

I like the interface that Gnome Builder  uses for organizing documents, but I want to hear your thoughts on this.

**Comment by Mandarancio** [comment]
I like this way as well,  a sort of list or tree view on the left side (with the possibility to hide it when not needed) is probably the best way. In particular today with most of the monitors with much more horizontal space than vertical. 

I  will look in the builder codebase to see what widgets they used(I believe a GtkPanedView + a GtkTreeView)  and how they implemented the project tree.
