### ISSUE TITLE
Add full screen or distraction free view

### ISSUE THREAD

**Issue by eldelacajita** [fabiocolacio/Marker#48]
Hi. This is the only GTK3 markdown editor I've found, and it's looking great so far! Keep up the good work! Here's a possible improvement:

It would be great to have a fullscreen mode. The most basic way of doing this could be just keeping the current view, stretching it to fullscreen and removing all the other elements of the interface, like any other app does. 

A nicer approach would be to provide an improved "distraction-free" environment. While still keeping the current view, it could improve the presentation, for example adding margins to the editing panel, centering the line you're editing, etc.

**Comment by fabiocolacio** [comment]
Thanks for the input! I will see what I can do. A popular feature in other editors dims all text except for the current sentence/paragraph. This could also be included in the presentation-mode/focus-mode. If something like this is implemented I will likely add a preferences pane so users can fine tune how the whole focus-mode experience works.

**Comment by fabiocolacio** [comment]
A basic fullscreen mode has been implemented (it can be accessed by pressing ``F11``), but is still lacking in many ways.

The headerbar cannot be accessed without exiting fullscreen mode. The preferred behavior should be more like Gedit's full-screen mode, where moving the cursor to the top of the screen causes it to appear.

**Comment by eldelacajita** [comment]
Hey! This is great, I just tried it, and it *is* an improvement. I totally agree that a Gedit-like behaviour would be great.
