### ISSUE TITLE
New settings schema error

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#56]
Hi,
Since when I recompiled the last changes I can not run Marker as it crash when it tries to read the "mathjax-toggle" settings:
```
(com.github.fabiocolacio.marker:32101): GLib-GIO-ERROR **: Settings schema 'com.github.fabiocolacio.marker.preferences.preview' does not contain a key named 'mathjax-toggle'
```
What can I do?

Cheers,
M

**Comment by fabiocolacio** [comment]
I added a preference option to enable/disable MathJax. This requires the GSchema to be reinstalled to your system. To do this you have to re-configure and re-install the project.

In other words delete the ``build`` directory, then run through the build instructions in the readme again, including the ``sudo ninja install`` step.

GSettings schemas have to be installed to a certain location in the system so the app knows where to find settings, which means every time the schemas are changed, the application has to be re-installed.

**Comment by Mandarancio** [comment]
Thanks!

**Comment by RoyiAvital** [comment]
@fabiocolacio , Does @Marker use MathJaX or KaTeX?
Even better, could it use both and let the user choose?

As MathJaX has much features not available in KaTeX.

Thank You.

**Comment by Mandarancio** [comment]
At the moment it use KaTeX as MathJaX is much slower, and so not so practical for (near) real-time rendering. 
What are the features missing in KaTeX?

**Comment by RoyiAvital** [comment]
I don't know why people say MathJaX isn't fast enough for real time rendering.
I use it and it works like charm (In VS Code Extension).

KaTeX doesn't support any environment (Such as `align`, `equation`, etc...) which are all supported by MathJaX.
It would be great to have an option to chose whether to use MathJaX or KaTeX (With KaTeX being the default).

**Comment by fabiocolacio** [comment]
Hi @RoyiAvital,

MathJaX is what we used initially, and it made the preview window in *Marker* very laggy. The performance was significantly improved when switching to KaTeX. With that being said, I am willing to perform some more tests with MathJaX, and see if there is a way to improve performance, and I will reconsider bundling it with Marker.

In addition, I think it is a good idea to add a section in the preferences allowing users to link their own javascripts and css styles. Even if MathJaX does not get bundled with a future release of Marker, the addition of this feature will still allow you to add MathJaX support yourself. I will open a new issue regarding this feature.

**Comment by Mandarancio** [comment]
I added the possibility to the user to choose between `katex` and `mathjax` in the parameters, however the difference is noticeable.

Let me know if there is any issue!

**Comment by RoyiAvital** [comment]
Wow!
You're fast.

How can I test it?
I usually use your Flathub Package in Linux Mint.

Thank You.

**Comment by Mandarancio** [comment]
There are 2 options:

 1. Wait for the next release on Flathub (it will come soon hopefully)
 2. Compile it and install it manually :
```bash
$ git clone https://github.com/fabiocolacio/Marker.git
$ cd Marker
$ git submodule update --init --recursive
$ mkdir build && cd build
$ meson .. --prefix /usr
$ ninja
$ sudo ninja install
```
