### ISSUE TITLE
Add a preference option to change or disable syntax themes for code blocks

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#61]
It appears as though highlight.js can have multiple themes. The user should be able to switch between them or disable it all together.

**Comment by Mandarancio** [comment]
To disable it there is already a toggle button, I added (in the #62 ) a combo-box to choose the theme.

I included ```marker-prefs.h``` in ```marker-markdown.c``` to avoid to add a new argument to all the functions (in this way I retrieve the highlight theme directly in the function). 
If you prefer to add an argument instead just tell me.
