### ISSUE TITLE
Restore toggle for syntax highlight

### ISSUE THREAD

**Issue by Mandarancio** [fabiocolacio/Marker#69]
I find the combobox for the preview syntax highlight very misleading as the none option could just mean that there is no css theme and not that the javascript is disabled, moreover I would like to remember which theme I prefer even when the javascript is off. 
I suggest to use the toggle button to disable and enable the javascript and the combo for the css, but in addition I would disable the combo when the javascript is off.

**Comment by fabiocolacio** [comment]
I think this is a good idea. See my [comment](https://github.com/fabiocolacio/Marker/pull/72#issuecomment-355855891) from PR #72.

If we implement this for the highlighting, we should also change the CSS combo box to work the same way

**Comment by Mandarancio** [comment]
Fixed in #73
