### ISSUE TITLE
Intermittent issue populating the highlight-theme combo-box

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#77]
Sometimes when I click on the combo-box to change the highlight.js theme, the list does not appear, making it impossible to change themes. It is important to note that the selected theme still works, the error is just with the combo box setting its list model.

I have been unable to find the source of the problem so far, since it seems to be programmed the same way as every other combo box. I likely missed an important detail somewhere...

(Running Fedora 27)

**Comment by Mandarancio** [comment]
This is a common problem with gnome and long combobox list, I have the same problem in gnome-tweak and other application, you can still use the arrows to move and select the theme. 
Something the combo list appear somewhere else than where it should appear as well, but again it depends on the gtk3.

**Comment by fabiocolacio** [comment]
I am closing this issue since it is an upstream bug.
