### ISSUE TITLE
Expand figures to more than just images

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#90]
It would be nice if code blocks could act as figures with a figure number and a caption, especially with mermaid diagrams.

**Comment by Mandarancio** [comment]
I added the figure numbering to mermaid diagram and added a listing to the codeblock as in [LaTeX](https://it.sharelatex.com/learn/Code_listing)
![figure_code_listing](https://user-images.githubusercontent.com/276686/34764486-f9540bd8-f5ee-11e7-969d-fc27828218a2.png)

**Comment by jocap** [comment]
@Mandarancio: Is there any way to add a title to a listing, like you can with figures, or should I open an issue about this?

**Comment by Mandarancio** [comment]
Hi @jocap I'm working in expanding the Markdown syntax to add labels to listing, tables, plots and as well as references, such to be compatible with [scholarly markdown](http://scholarlymarkdown.com/)

**Comment by jocap** [comment]
@Mandarancio: Sounds great :-) Good luck!

**Comment by Mandarancio** [comment]
This issue is merged with #145
