### ISSUE TITLE
Create a HACKING.md file

### ISSUE THREAD

**Issue by fabiocolacio** [fabiocolacio/Marker#98]
It would contain guidelines for newly written code. Here is an example of the one in the [gnome-calendar project](https://gitlab.gnome.org/GNOME/gnome-calendar/blob/master/HACKING.md).

When I started this project, I was still learning Gtk, so a lot of the code was unorganized/messy, but I would like newly written code to follow certain standards, especially with the big changes on the way. This makes it easier to read and navigate.

These guidelines would of course only apply to the main codebase  (the ``marker-*`` files) and not the dependencies like hoedown or charter.

**Comment by Mandarancio** [comment]
I think is a very good idea! I never used Gtk and I mostly write code in C++ or python so it can be very useful!

**Comment by fabiocolacio** [comment]
I added the file in commit https://github.com/fabiocolacio/Marker/commit/91d81f3c894a1c02da3bcd204ba6729b52d77266 and named it CONTRIBUTING instead of HACKING.

I based it off of the one I linked above, with a few of my own changes.
